### PR TITLE
Clean up reddit: #567

### PR DESCRIPTION
**Pull request by phu-pmh**
remove reddit related stuffs from `models.py`

### CODE REVIEW

**Comment by sleepinyourhat** [comment]
@W4ngatang

**Comment by W4ngatang** [comment]
@sleepinyourhat can you take a look at this? I told Phu it'd be okay to remove all the generation-tasks-recast-as-classification (RedditClassification, MTClassification, etc.) as well as the Reddit ranking task. Does that sound right?

**Comment by sleepinyourhat** [comment]
Hrm, we should leave in the ones that appear in the ACL submission. I'm pretty sure that includes Reddit-as-classification.

**Comment by W4ngatang** [comment]
@sleepinyourhat We got rid of it for the ACL submission. Should be okay to delete then?

In any case, @phu-pmh could you merge master into this branch?

**Pull request merged**
