### PR TITLE
Add PDFs of edge probing posters

### PR DESCRIPTION
**Pull request by iftenney**

### CODE REVIEW

**Comment by sleepinyourhat** [comment]
I'd prefer to put this elsewhere and add a link—we're encouraging a fairly large group of potential users to clone/download the repo, and it seems odd to require that they download non-trivial paper content as well. Make an edgeprobing repo or GitHub Pages site?

**Comment by iftenney** [comment]
SG - I'll make a pages site.

**Comment by sleepinyourhat** [comment]
Ready to merge/close soon?

**Comment by iftenney** [comment]
Sorry - got tied up in some other things. Closing for now, I'll re-open after hosting them somewhere else.

**Comment by iftenney** [comment]
Ok, updated links. (And finally made myself a website ;) )

**Pull request merged**
