### PR TITLE
Cleaning up src/modules/modules.py into several files.

### LINKED ISSUE #420: Clean up modules.py
I won't get to this until after the ICLR deadline, but I'd like to clean up the `src/` directory so dependencies are a bit cleaner. Also, `tasks.py` is massive and we should really split it up.

Proposed structure:
```
src/
    allennlp_mods/
    cove/ [submodule]
    __init__.py
    evaluate.py
    models.py
    modules/
        cnns/
        __init__.py
        <several .py files with old contents of modules.py>
        edge_probing.py
        seq2seq_decoder.py
        generate_s2s.py
    preprocess.py
    tasks/
        __init__.py
        tasks.py    # core definitions and registry
        edge_probing.py
        <other .py files containing various groups of tasks>
    trainer.py
    utils/    # or "misc/" or "lib/"
        __init__.py
        config.py
        emails.py
        gcp.py
        hocon_writer.py
        retokenize.py
        serialize.py
        utils.py
```

### PR DESCRIPTION
**Pull request by Narsil**
Fixes #420

### CODE REVIEW

**Comment by sleepinyourhat** [comment]
Great, thanks for putting this together!

Just to know what to look for, did this require any changes to the method bodies, or was it only a matter of moving code and adjusting import statements?

**Comment by Narsil** [comment]
Just moved code around.
I removed some dead imports too (not all).

I just added the import test to check I did not break anything as I did not know how to test properly this bit of code.

**Comment by sleepinyourhat** [comment]
Thanks! If tests are passing, I'm comfortable merging. It'd be nice to test every module (we don't have that much test coverage yet), but that can wait, since HEAD is a bit messy anyhow.

**Comment by sleepinyourhat** [comment]
I'm getting a bunch of import errors in standard configs—for example, sentence_encoder.py uses TimeDistributed and Highway without importing them. Mind importing everything everywhere to start, and only pruning the clearly unneeded imports?

**Comment by sleepinyourhat** [comment]
(Reverted)

**Comment by Narsil** [comment]
How can I test, which configs are problematic ?
I'll double check all imports.

**Comment by Narsil** [comment]
I created a new version here that I checked with tools:
https://github.com/nyu-mll/jiant/pull/753

May I suggest to use flake8 as pre-commit hook + circle-ci ?

**Pull request merged**
