### PR TITLE
adversarial_nli -> adversarial-nli, SocialIQA -> socialiqa

### PR DESCRIPTION
**Pull request by HaokunLiu**

### CODE REVIEW

**Comment by pyeres** [comment]
Thanks @HaokunLiu — are there reasons not to include `wiki103_classif` and `seg_wix`?

**Comment by HaokunLiu** [comment]
Oops. I forgot to change that, sorry. Could you update those names? I’m on
the train.

**Comment by pyeres** [comment]
> Oops. I forgot to change that, sorry. Could you update those names? I’m on the train.

Sure, `seg-wix` and `wiki103-classif` are addressed by ad1dfb7.

**Comment by HaokunLiu** [comment]
> When I searched for `seg_wix` (pre- [ad1dfb7](https://github.com/nyu-mll/jiant/commit/ad1dfb7a473c7c6a962ddc029fccdb0acac872ba)), I noticed that that name string appears outside the `tasks.py` file (in a config and var). Can you confirm that the names you're changing with this PR have been replaced project-wide (beyond the task decorators)?

Good catch. Yes, there are other places. I have updated those ones.

**Pull request merged**
