### PR TITLE
Updates to support using MiniBERTas as input_module

### PR DESCRIPTION
**Pull request by YianZhang**
We pretrained RoBERTa on limited amounts of data, and released the model checkpoints on Huggingface Transformers. This PR will allow jiant to use MiniBERTas as input_module and will support edge probing with MiniBERTas.

### CODE REVIEW

**Comment by YianZhang** [comment]
@sleepinyourhat I tested nyu-mll/roberta-base-1B-3, roberta-base, and bert-base-uncased on the edge probing dependency labeling task. All experiments can be run with no errors; all models achieve reasonable f1 (~95). The miniberta model downloads automatically.

**Comment by YianZhang** [comment]
@sleepinyourhat Thanks for the feedback! What about now? I fixed all the style issues reported by pep8speaks except for those that are not caused by my commits.

**Comment by sleepinyourhat** [comment]
Merging. FWIW, We're hoping to talk more soon about how to do things like this in jiant 2, which should come out in some form (alpha?) next week, since we'd like to treat it as less of a core feature, but still leave it usable.

**Comment by YianZhang** [comment]
@sleepinyourhat Great! Let me know then how I can be of help.

**Comment by sleepinyourhat** [comment]
Possibly now relevant to @phu-pmh, CC @jeswan.

**Comment by sleepinyourhat** [comment]
(As a jiant 1.x example of something we might need to do in jiant 2.x)

**Pull request merged**
