### PR TITLE
Increasing sample size for MLM test

### PR DESCRIPTION
**Pull request by pruksmhc**
This PR addresses https://github.com/nyu-mll/jiant/issues/1076
Because this is a statistical test, this PR increases the length of input passed in and number of examples to average over in order, as well as slightly increase the error boundary around the masking ratio in order to decrease the amount of failed tests. 
I tested this by running the MLM test 15 times with all successes.

### CODE REVIEW

**Comment by zphang** [comment]
How about making the test deterministic with seeds?

From a quick look, setting the random seed of `random` and `torch` should cover all sources of randomness.

**Comment by pruksmhc** [comment]
I think torch.bernoulli could be made more deterministic with the seed, but I just took out the random.randint that produced the length (just because I don't think there's much you lose by setting it to a large number).

**Comment by pyeres** [comment]
@pruksmhc — @zphang's suggestion should only require adding two lines [at line L77](https://github.com/nyu-mll/jiant/blob/67238afad48b3f71463a54debe7e9d2047636d92/tests/tasks/test_mlm.py#L77):

```
torch.manual_seed(0)
random.seed(0)
```

With the additional length/iteration in your PR lines L79-L80 this one test takes a couple seconds on my laptop — people generally try to keep the total time to run all their unit tests together to less than a second. If you want to add this additional time, I want to check that we're getting something beyond what we can accomplish with the seeds alone.

**Comment by pruksmhc** [comment]
Alright, I just increased the length of each sample instead of increasing the number of samples.

**Pull request merged**
